services:
  app:
    build: .
    container_name: health-care-backend
    image: mini-heath-care:dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    command: ["pm2-runtime", "start", "src/server.js"]
    networks:
      - minimi_backend_app_network
    restart: unless-stopped

networks:
  minimi_backend_app_network:
    driver: bridge
