services:
  app:
    build: .
    container_name: health-care-backend
    image: mini-heath-care:dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=Development
    restart: unless-stopped
